// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: instruction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeriesOfSteps_ResponseGenerator int32

const (
	// default
	SeriesOfSteps_RESPONSE_GENERATOR_UNSPECIFIED SeriesOfSteps_ResponseGenerator = 0
	SeriesOfSteps_RESPONSE_GENERATOR_CONCAT      SeriesOfSteps_ResponseGenerator = 1
)

// Enum value maps for SeriesOfSteps_ResponseGenerator.
var (
	SeriesOfSteps_ResponseGenerator_name = map[int32]string{
		0: "RESPONSE_GENERATOR_UNSPECIFIED",
		1: "RESPONSE_GENERATOR_CONCAT",
	}
	SeriesOfSteps_ResponseGenerator_value = map[string]int32{
		"RESPONSE_GENERATOR_UNSPECIFIED": 0,
		"RESPONSE_GENERATOR_CONCAT":      1,
	}
)

func (x SeriesOfSteps_ResponseGenerator) Enum() *SeriesOfSteps_ResponseGenerator {
	p := new(SeriesOfSteps_ResponseGenerator)
	*p = x
	return p
}

func (x SeriesOfSteps_ResponseGenerator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeriesOfSteps_ResponseGenerator) Descriptor() protoreflect.EnumDescriptor {
	return file_instruction_proto_enumTypes[0].Descriptor()
}

func (SeriesOfSteps_ResponseGenerator) Type() protoreflect.EnumType {
	return &file_instruction_proto_enumTypes[0]
}

func (x SeriesOfSteps_ResponseGenerator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeriesOfSteps_ResponseGenerator.Descriptor instead.
func (SeriesOfSteps_ResponseGenerator) EnumDescriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{6, 0}
}

type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what should the "agent" do
	//
	// Types that are valid to be assigned to Step:
	//
	//	*Instruction_CallAgent
	//	*Instruction_ReturnResponse
	//	*Instruction_Steps
	Step          isInstruction_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_instruction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetStep() isInstruction_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *Instruction) GetCallAgent() *CallAgent {
	if x != nil {
		if x, ok := x.Step.(*Instruction_CallAgent); ok {
			return x.CallAgent
		}
	}
	return nil
}

func (x *Instruction) GetReturnResponse() *ReturnResponse {
	if x != nil {
		if x, ok := x.Step.(*Instruction_ReturnResponse); ok {
			return x.ReturnResponse
		}
	}
	return nil
}

func (x *Instruction) GetSteps() *SeriesOfSteps {
	if x != nil {
		if x, ok := x.Step.(*Instruction_Steps); ok {
			return x.Steps
		}
	}
	return nil
}

type isInstruction_Step interface {
	isInstruction_Step()
}

type Instruction_CallAgent struct {
	CallAgent *CallAgent `protobuf:"bytes,1,opt,name=call_agent,json=callAgent,proto3,oneof"`
}

type Instruction_ReturnResponse struct {
	ReturnResponse *ReturnResponse `protobuf:"bytes,2,opt,name=return_response,json=returnResponse,proto3,oneof"`
}

type Instruction_Steps struct {
	Steps *SeriesOfSteps `protobuf:"bytes,3,opt,name=steps,proto3,oneof"`
}

func (*Instruction_CallAgent) isInstruction_Step() {}

func (*Instruction_ReturnResponse) isInstruction_Step() {}

func (*Instruction_Steps) isInstruction_Step() {}

// Behavior messages
type SendMessageBehavior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageBehavior) Reset() {
	*x = SendMessageBehavior{}
	mi := &file_instruction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageBehavior) ProtoMessage() {}

func (x *SendMessageBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageBehavior.ProtoReflect.Descriptor instead.
func (*SendMessageBehavior) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{1}
}

type PushNotificationBehavior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushNotificationBehavior) Reset() {
	*x = PushNotificationBehavior{}
	mi := &file_instruction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushNotificationBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushNotificationBehavior) ProtoMessage() {}

func (x *PushNotificationBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushNotificationBehavior.ProtoReflect.Descriptor instead.
func (*PushNotificationBehavior) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{2}
}

func (x *PushNotificationBehavior) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ResubscribeBehavior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResubscribeBehavior) Reset() {
	*x = ResubscribeBehavior{}
	mi := &file_instruction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResubscribeBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResubscribeBehavior) ProtoMessage() {}

func (x *ResubscribeBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResubscribeBehavior.ProtoReflect.Descriptor instead.
func (*ResubscribeBehavior) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{3}
}

// gets the agent card from a remote agent, calls it and returns the response
type CallAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// which transport use to get agent card and later call
	Transport string `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	// where to get the agent card from
	AgentCardUri string `protobuf:"bytes,2,opt,name=agent_card_uri,json=agentCardUri,proto3" json:"agent_card_uri,omitempty"`
	// instruction for the called agent
	Instruction *Instruction `protobuf:"bytes,3,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// whether to use streaming
	Streaming bool `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// behavior mode
	//
	// Types that are valid to be assigned to Behavior:
	//
	//	*CallAgent_SendMessage
	//	*CallAgent_PushNotification
	//	*CallAgent_Resubscribe
	Behavior      isCallAgent_Behavior `protobuf_oneof:"behavior"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAgent) Reset() {
	*x = CallAgent{}
	mi := &file_instruction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAgent) ProtoMessage() {}

func (x *CallAgent) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAgent.ProtoReflect.Descriptor instead.
func (*CallAgent) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{4}
}

func (x *CallAgent) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *CallAgent) GetAgentCardUri() string {
	if x != nil {
		return x.AgentCardUri
	}
	return ""
}

func (x *CallAgent) GetInstruction() *Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *CallAgent) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *CallAgent) GetBehavior() isCallAgent_Behavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

func (x *CallAgent) GetSendMessage() *SendMessageBehavior {
	if x != nil {
		if x, ok := x.Behavior.(*CallAgent_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *CallAgent) GetPushNotification() *PushNotificationBehavior {
	if x != nil {
		if x, ok := x.Behavior.(*CallAgent_PushNotification); ok {
			return x.PushNotification
		}
	}
	return nil
}

func (x *CallAgent) GetResubscribe() *ResubscribeBehavior {
	if x != nil {
		if x, ok := x.Behavior.(*CallAgent_Resubscribe); ok {
			return x.Resubscribe
		}
	}
	return nil
}

type isCallAgent_Behavior interface {
	isCallAgent_Behavior()
}

type CallAgent_SendMessage struct {
	SendMessage *SendMessageBehavior `protobuf:"bytes,5,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type CallAgent_PushNotification struct {
	PushNotification *PushNotificationBehavior `protobuf:"bytes,6,opt,name=push_notification,json=pushNotification,proto3,oneof"`
}

type CallAgent_Resubscribe struct {
	Resubscribe *ResubscribeBehavior `protobuf:"bytes,7,opt,name=resubscribe,proto3,oneof"`
}

func (*CallAgent_SendMessage) isCallAgent_Behavior() {}

func (*CallAgent_PushNotification) isCallAgent_Behavior() {}

func (*CallAgent_Resubscribe) isCallAgent_Behavior() {}

// this option just returns a response
type ReturnResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what to return to the calling agent
	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// whether to hold the task in WORKING state instead of completing it
	HoldTask      bool `protobuf:"varint,2,opt,name=hold_task,json=holdTask,proto3" json:"hold_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnResponse) Reset() {
	*x = ReturnResponse{}
	mi := &file_instruction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnResponse) ProtoMessage() {}

func (x *ReturnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnResponse.ProtoReflect.Descriptor instead.
func (*ReturnResponse) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ReturnResponse) GetHoldTask() bool {
	if x != nil {
		return x.HoldTask
	}
	return false
}

// executes step series and returns response based on response_generator
type SeriesOfSteps struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	Instructions      []*Instruction                  `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	ResponseGenerator SeriesOfSteps_ResponseGenerator `protobuf:"varint,2,opt,name=response_generator,json=responseGenerator,proto3,enum=itk.SeriesOfSteps_ResponseGenerator" json:"response_generator,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SeriesOfSteps) Reset() {
	*x = SeriesOfSteps{}
	mi := &file_instruction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesOfSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesOfSteps) ProtoMessage() {}

func (x *SeriesOfSteps) ProtoReflect() protoreflect.Message {
	mi := &file_instruction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesOfSteps.ProtoReflect.Descriptor instead.
func (*SeriesOfSteps) Descriptor() ([]byte, []int) {
	return file_instruction_proto_rawDescGZIP(), []int{6}
}

func (x *SeriesOfSteps) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *SeriesOfSteps) GetResponseGenerator() SeriesOfSteps_ResponseGenerator {
	if x != nil {
		return x.ResponseGenerator
	}
	return SeriesOfSteps_RESPONSE_GENERATOR_UNSPECIFIED
}

var File_instruction_proto protoreflect.FileDescriptor

const file_instruction_proto_rawDesc = "" +
	"\n" +
	"\x11instruction.proto\x12\x03itk\"\xb2\x01\n" +
	"\vInstruction\x12/\n" +
	"\n" +
	"call_agent\x18\x01 \x01(\v2\x0e.itk.CallAgentH\x00R\tcallAgent\x12>\n" +
	"\x0freturn_response\x18\x02 \x01(\v2\x13.itk.ReturnResponseH\x00R\x0ereturnResponse\x12*\n" +
	"\x05steps\x18\x03 \x01(\v2\x12.itk.SeriesOfStepsH\x00R\x05stepsB\x06\n" +
	"\x04step\"\x15\n" +
	"\x13SendMessageBehavior\",\n" +
	"\x18PushNotificationBehavior\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x15\n" +
	"\x13ResubscribeBehavior\"\xf8\x02\n" +
	"\tCallAgent\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12$\n" +
	"\x0eagent_card_uri\x18\x02 \x01(\tR\fagentCardUri\x122\n" +
	"\vinstruction\x18\x03 \x01(\v2\x10.itk.InstructionR\vinstruction\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12=\n" +
	"\fsend_message\x18\x05 \x01(\v2\x18.itk.SendMessageBehaviorH\x00R\vsendMessage\x12L\n" +
	"\x11push_notification\x18\x06 \x01(\v2\x1d.itk.PushNotificationBehaviorH\x00R\x10pushNotification\x12<\n" +
	"\vresubscribe\x18\a \x01(\v2\x18.itk.ResubscribeBehaviorH\x00R\vresubscribeB\n" +
	"\n" +
	"\bbehavior\"I\n" +
	"\x0eReturnResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1b\n" +
	"\thold_task\x18\x02 \x01(\bR\bholdTask\"\xf2\x01\n" +
	"\rSeriesOfSteps\x124\n" +
	"\finstructions\x18\x01 \x03(\v2\x10.itk.InstructionR\finstructions\x12S\n" +
	"\x12response_generator\x18\x02 \x01(\x0e2$.itk.SeriesOfSteps.ResponseGeneratorR\x11responseGenerator\"V\n" +
	"\x11ResponseGenerator\x12\"\n" +
	"\x1eRESPONSE_GENERATOR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESPONSE_GENERATOR_CONCAT\x10\x01b\x06proto3"

var (
	file_instruction_proto_rawDescOnce sync.Once
	file_instruction_proto_rawDescData []byte
)

func file_instruction_proto_rawDescGZIP() []byte {
	file_instruction_proto_rawDescOnce.Do(func() {
		file_instruction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instruction_proto_rawDesc), len(file_instruction_proto_rawDesc)))
	})
	return file_instruction_proto_rawDescData
}

var file_instruction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_instruction_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_instruction_proto_goTypes = []any{
	(SeriesOfSteps_ResponseGenerator)(0), // 0: itk.SeriesOfSteps.ResponseGenerator
	(*Instruction)(nil),                  // 1: itk.Instruction
	(*SendMessageBehavior)(nil),          // 2: itk.SendMessageBehavior
	(*PushNotificationBehavior)(nil),     // 3: itk.PushNotificationBehavior
	(*ResubscribeBehavior)(nil),          // 4: itk.ResubscribeBehavior
	(*CallAgent)(nil),                    // 5: itk.CallAgent
	(*ReturnResponse)(nil),               // 6: itk.ReturnResponse
	(*SeriesOfSteps)(nil),                // 7: itk.SeriesOfSteps
}
var file_instruction_proto_depIdxs = []int32{
	5, // 0: itk.Instruction.call_agent:type_name -> itk.CallAgent
	6, // 1: itk.Instruction.return_response:type_name -> itk.ReturnResponse
	7, // 2: itk.Instruction.steps:type_name -> itk.SeriesOfSteps
	1, // 3: itk.CallAgent.instruction:type_name -> itk.Instruction
	2, // 4: itk.CallAgent.send_message:type_name -> itk.SendMessageBehavior
	3, // 5: itk.CallAgent.push_notification:type_name -> itk.PushNotificationBehavior
	4, // 6: itk.CallAgent.resubscribe:type_name -> itk.ResubscribeBehavior
	1, // 7: itk.SeriesOfSteps.instructions:type_name -> itk.Instruction
	0, // 8: itk.SeriesOfSteps.response_generator:type_name -> itk.SeriesOfSteps.ResponseGenerator
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_instruction_proto_init() }
func file_instruction_proto_init() {
	if File_instruction_proto != nil {
		return
	}
	file_instruction_proto_msgTypes[0].OneofWrappers = []any{
		(*Instruction_CallAgent)(nil),
		(*Instruction_ReturnResponse)(nil),
		(*Instruction_Steps)(nil),
	}
	file_instruction_proto_msgTypes[4].OneofWrappers = []any{
		(*CallAgent_SendMessage)(nil),
		(*CallAgent_PushNotification)(nil),
		(*CallAgent_Resubscribe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instruction_proto_rawDesc), len(file_instruction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instruction_proto_goTypes,
		DependencyIndexes: file_instruction_proto_depIdxs,
		EnumInfos:         file_instruction_proto_enumTypes,
		MessageInfos:      file_instruction_proto_msgTypes,
	}.Build()
	File_instruction_proto = out.File
	file_instruction_proto_goTypes = nil
	file_instruction_proto_depIdxs = nil
}
